version: '3'
services:
  chord-node-1:
    build: .
    container_name: chord-node-1
    ports:
      - "8001:8001"  
      - "8101:8002" # Puerto para el debugger
    command: ["python", "-Xfrozen_modules=off" ,"-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:8002", "chord_node.py"]
  chord-node-2:
    build: .
    container_name: chord-node-2
    ports:
      - "8002:8001"  # Mapea el puerto 8002 del host al puerto 8001 del contenedor
      - "8102:8002"
    #command: ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5679", "chord_node.py"]
    command: ["python", "-Xfrozen_modules=off" ,"-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:8002", "chord_node.py"]

  chord-node-3:
    build: .
    container_name: chord-node-3
    ports:
      - "8003:8001"  # Mapea el puerto 8003 del host al puerto 8001 del contenedor
      - "8103:8002"
    #command: ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5680", "chord_node.py"]
    command: ["python", "-Xfrozen_modules=off" ,"-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:8002", "chord_node.py"]
